version: '1.0'

services:
  keycloak:
    image: jboss/keycloak
    container_name: "keycloak"
    ports:
      - "8080:8080"
    volumes:
      - your_path/keycloak-docker/keycloak-realm.json:/tmp/keycloak-realm.json #change your_path 
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/keycloak-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
  rest:
    image: bookme #registry.infres.fr/bookme
    build: .
    container_name: "bookme"
    ports:
      - "8090:8080"
