apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookme-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: bookme.infres.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookme-service
                port:
                  number: 8080

apiVersion: v1
kind: Service
metadata:
  name: bookme-service
  labels:
    run: bookme
spec:
  selector:
    app: bookme
  ports:
    - protocol: TCP
      port: 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookme
  labels:
    app: MyService
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookme
  template:
    metadata:
      labels:
        app: bookme
    spec:
      containers:
        - name: bookme
          image: registry.infres.fr/bookme
          imagePullPolicy: Always
          command: []
          ports:
            - containerPort: 8080